//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17
#[allow(unused_imports)]
pub use super::api::Entity as Api;
pub use super::dnc_user::Entity as DncUser;
pub use super::role::Entity as Role;
pub use super::role_api::Entity as RoleApi;
